TIBCOSoftware/platform-provisioner

- charts/common-dependency/Chart.yaml
- charts/common-dependency/scripts/_functions.sh
Address the issue that the pipeline always need github token for all repos
> [PDP-2797] adjust git clone for public repo

- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
- docs/recipes/k8s/cloud/deploy-tp-eks.yaml
Updated dp-config-aws, dp-config-aks, dp-config-es chart versions in recipe to latest from https://github.com/TIBCOSoftware/tp-helm-charts/blob/main/charts
> Updated dp-config chart versions

- docs/recipes/k8s/cloud/aks.md
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
Address Azure auth issue and the usage of internal variable
> [PDP-2861] fix azure recipe issue

- charts/common-dependency/Chart.yaml
- charts/common-dependency/scripts/_functions.sh
- charts/helm-install/Chart.yaml
- charts/helm-install/scripts/_funcs_helm.sh
- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- dev/platform-provisioner-install.sh
- dev/platform-provisioner-pipelinerun.sh
- dev/platform-provisioner-test.sh
- docker/Dockerfile
- docker/build.sh
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/k8s/cloud/aks.md
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
- docs/recipes/k8s/cloud/deploy-tp-eks.yaml
- docs/recipes/k8s/cloud/deploy-tp-gke.yaml
- docs/recipes/k8s/cloud/eks.md
- docs/recipes/k8s/cloud/gke.md
- docs/recipes/k8s/cloud/scripts/gke/create-gke.sh
- docs/recipes/k8s/cloud/scripts/gke/delete-gke.sh
- docs/recipes/k8s/cloud/scripts/gke/prepare-gke-sa.sh
- docs/recipes/tests/test-gcp.yaml
* Add vcluster support for helm-install pipelines
* Add external registry support
* Upgrade Dockerfile
* And fix small bugs
> [PDP-3120] Add GKE support

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
Add ingress class and fix typo
> [PDP-3191] add ingress class

- charts/common-dependency/Chart.yaml
- charts/common-dependency/scripts/_functions.sh
- charts/common-dependency/scripts/shared.cue
- charts/common-dependency/templates/secret-github.yaml
- charts/common-dependency/values.yaml
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
- docs/recipes/k8s/cloud/deploy-tp-eks.yaml
- docs/recipes/k8s/cloud/deploy-tp-gke.yaml
- docs/recipes/k8s/on-prem/minikube.md
* Add pipeline env default value
* remove the env rule on cue so the pipeline env can work with bash default value
* Add traefik support
> [PDP-3293][PDP-3191] update with traefik and recipe validation change

- .github/workflows/docker-image-ghcr-build-push.yml
- dev/platform-provisioner-install.sh
- dev/platform-provisioner.sh
remove docker hub private repo
> add provisioner docker image to ghcr public repo

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/menuContent.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/config/pp-deploy-tp-base-on-prem-cert.yaml
- charts/provisioner-config-local/config/pp-deploy-tp-base-on-prem.yaml
- charts/provisioner-config-local/config/pp-maintain-tp-admin-email.yaml
- charts/provisioner-config-local/config/pp-maintain-tp-config-coredns.yaml
- charts/provisioner-config-local/config/pp-maintain-tp-reset-postgres-db.yaml
- charts/provisioner-config-local/config/pp-undeploy-cp.yaml
- charts/provisioner-config-local/config/pp-undeploy-dp.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem-https.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem.yaml
- dev/platform-provisioner-install.sh
- dev/platform-provisioner.sh
- docker/Dockerfile
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
- docs/recipes/k8s/cloud/deploy-tp-gke.yaml
* expose more options from recipe
* refactor recipe with sections for new GUI
* add create admin user pipeline
* add config CoreDNS pipeline
* switch script to use TIBCOSoftware public repo by default
* upgrade base pipeline docker image
> [PCP-7649] Update recipe

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-upgrade.yaml
- charts/provisioner-config-local/config/pp-deploy-tp-base-on-prem-cert.yaml
- charts/provisioner-config-local/config/pp-deploy-tp-base-on-prem.yaml
- charts/provisioner-config-local/config/pp-maintain-tp-config-coredns.yaml
- charts/provisioner-config-local/config/pp-maintain-tp-reset-postgres-db.yaml
- charts/provisioner-config-local/config/pp-o11y-dp-config-es.yaml
- charts/provisioner-config-local/config/pp-o11y-full.yaml
- charts/provisioner-config-local/config/pp-register-dp-private.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem-https.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem.yaml
- dev/platform-provisioner.sh
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
- docs/recipes/k8s/cloud/deploy-tp-eks.yaml
- docs/recipes/k8s/cloud/deploy-tp-gke.yaml
- docs/recipes/k8s/cloud/scripts/aks/create-aks.sh
- docs/recipes/k8s/on-prem/kind.md
- docs/recipes/k8s/on-prem/microk8s.md
- docs/recipes/k8s/on-prem/minikube.md
- docs/recipes/tests/test-container-binaries.yaml
- docs/recipes/tp-base/tp-base-on-prem-https.yaml
- docs/recipes/tp-base/tp-base-on-prem.yaml
* upgrade other third party tools as well. 
* enhance platform upgrade pipeline
* fix CP admin email chart values
* fix azure public ip address issue
* add test container binary pipeline
* adjust recipes and GUI menu items
> [PCP-7686] Upgrade to Postgres 16

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-ingress-tracing.yaml
- charts/provisioner-config-local/config/pp-o11y-dp-config-es.yaml
- charts/provisioner-config-local/config/pp-o11y-full.yaml
- charts/provisioner-config-local/config/pp-o11y-otel-daemon.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- docs/recipes/controlplane/tp-cp.yaml
* upgrade o11y version
* fix the prometheus node exporter restart issue
* remove the helm version
> [PDP-3532] remove dpMetadata

- charts/common-dependency/Chart.yaml
- charts/common-dependency/scripts/_functions.sh
- charts/helm-install/Chart.yaml
- charts/helm-install/scripts/check.cue
- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem-https.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem.yaml
- dev/platform-provisioner-install.sh
- dev/platform-provisioner-test.sh
- dev/platform-provisioner.sh
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
Changes
* [PDP-3637] update for TP HF3
* [PDP-3523] remove CP_PROVIDER
* [PCP-4890] put maildev in a generic helm chart
* fix null validation for helm chart user name and password
* externalize YQ CLI command name (Inside container we use yq4. Now move as env)
* Format on-perm GUI text
* Add support to run platform provisioner headless on windows git bash
> [PDP-3523] 2024 week 51 update

- dev/platform-provisioner-test.sh
- dev/platform-provisioner.sh
If the target folder not exist; the docker run will fail. Need to check if folder exist.
> add option for mount folder

- charts/generic-runner/Chart.yaml
- charts/generic-runner/scripts/run.sh
- charts/helm-install/Chart.yaml
- charts/helm-install/scripts/run.sh
- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/menuContent.yaml
- charts/provisioner-config-local/config/pp-maintain-tp-automation-o11y.yaml
- charts/provisioner-config-local/recipes/tp-automation-o11y.yaml
- charts/provisioner-config-local/scripts/o11y/README.md
- charts/provisioner-config-local/scripts/o11y/color_logger.py
- charts/provisioner-config-local/scripts/o11y/flogo.json
- charts/provisioner-config-local/scripts/o11y/requirements.txt
- charts/provisioner-config-local/scripts/o11y/run.py
- charts/provisioner-config-local/scripts/o11y/run1.py
- charts/provisioner-config-local/scripts/o11y/util.py
- dev/platform-provisioner-install.sh
- dev/platform-provisioner-test.sh
- dev/platform-provisioner.sh
- docker/Dockerfile
- docker/Dockerfile-tester
- docs/recipes/automation/on-perm/README.md
- docs/recipes/automation/on-perm/generate-recipe.sh
- docs/recipes/automation/on-perm/run.sh
* add automation pipeline to support e2e provision of TP. (For more info see readme under docs/recipes/automation/on-perm/README.md)
* add option to not show input recipe for headless mode (less noise)
* optimize headless script for CI/CD usage
* @owen-pengtao  provide all the playwright python scripts
* Add `generate-recipe.sh` to generate recipes without GUI
* Add `run.sh` for e2e headless automation
> [PCP-8898] Initial support for TP automation

- charts/common-dependency/Chart.yaml
- charts/common-dependency/scripts/_funcs_generic_runner.sh
- charts/common-dependency/scripts/shared.cue
- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/tp-automation-o11y.yaml
- docs/recipes/automation/on-perm/gcp.sh
- docs/recipes/automation/on-perm/generate-recipe.sh
- docs/recipes/automation/on-perm/update-recipe-tokens.sh
- docs/recipes/automation/tp-setup/bootstrap/README.md
- docs/recipes/automation/tp-setup/bootstrap/env.py
- docs/recipes/automation/tp-setup/bootstrap/helper.py
- docs/recipes/automation/tp-setup/bootstrap/page_auth.py
- docs/recipes/automation/tp-setup/bootstrap/page_env.py
- docs/recipes/automation/tp-setup/bootstrap/report.py
- docs/recipes/automation/tp-setup/bootstrap/run.py
- docs/recipes/automation/tp-setup/bootstrap/util.py
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/tests/test-local.yaml
* Add customized repo support for CP 1.4
* Update auto setup script
* add new name field for task
> [PCP-9153] add customized helm repo support

- docs/recipes/automation/on-prem/adjust-ingress.sh
- docs/recipes/automation/on-prem/adjust-recipe.sh
- docs/recipes/automation/on-prem/generate-recipe.sh
- docs/recipes/automation/on-prem/run.sh
* fix the script option number
> [PCP-10800] adjust script options

- docs/recipes/automation/cloud/bastion/README.md
- docs/recipes/automation/cloud/bastion/SETUPDP.md
- docs/recipes/automation/cloud/bastion/_common.sh
- docs/recipes/automation/cloud/bastion/setup-dp-aks-platformprovisioner.sh
- docs/recipes/automation/cloud/bastion/setup-dp-eks-platformprovisioner.sh
- docs/recipes/automation/cloud/bastion/setup-dp-gke-platformprovisioner.sh
Added capability to override additional .meta.globalEnvVariable... properties in recipe from config.props and update documentation to align wth TIBCO Platform 1.5.0
> Release 20250327 of the Cloud Bastion Automation Scripts

- charts/helm-install/Chart.yaml
- charts/helm-install/docs/defaultValue.yaml
- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-upgrade.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/pp-o11y-full.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem-https.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem.yaml
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/k8s/cloud/deploy-tp-aks.yaml
- docs/recipes/k8s/cloud/deploy-tp-eks.yaml
- docs/recipes/k8s/cloud/deploy-tp-gke.yaml
- docs/recipes/tp-base/tp-base-on-prem-https.yaml
- docs/recipes/tp-base/tp-base-on-prem.yaml
* bump up version for TP 1.5.1 release
* upgrade nginx for CVE-2025-1974
* bump traefik version
* bump ES version
> [PCP-10942] bump version for 1.5.1

- charts/helm-install/Chart.yaml
- charts/helm-install/scripts/_funcs_helm.sh
- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/recipes/tp-deploy-bw5dm.yaml
- docs/recipes/automation/tp-setup/bootstrap/page_bmdp.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_bmdp_config.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_dataplane.py
- docs/recipes/automation/tp-setup/bootstrap/utils/env.py
- docs/recipes/automation/tp-setup/bootstrap/utils/report.py
- docs/recipes/controlplane/tp-cp.yaml
changes
* add oci support for helm-install pipeline
* enable CP logging by default
* add automation for BMDP
> 2025 week 14 update

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- docs/recipes/automation/on-prem/connect-ins.sh
- docs/recipes/automation/tp-setup/bootstrap/README.md
- docs/recipes/automation/tp-setup/bootstrap/e2e/conftest.py
- docs/recipes/automation/tp-setup/bootstrap/e2e/dataplane/configuration/o11y/test_test_connection_button.py
- docs/recipes/automation/tp-setup/bootstrap/e2e/observability/test_observability_list.py
- docs/recipes/automation/tp-setup/bootstrap/page_env.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_auth.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_dataplane.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_dp_flogo.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_global.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_o11y.py
- docs/recipes/automation/tp-setup/bootstrap/server.py
- docs/recipes/automation/tp-setup/bootstrap/templates/index.html
- docs/recipes/automation/tp-setup/bootstrap/utils/env.py
- docs/recipes/automation/tp-setup/bootstrap/utils/helper.py
- docs/recipes/automation/tp-setup/bootstrap/utils/util.py
* add support for CP logging as optional config
* add more automation
> 2025 week 15 update

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/recipes/tp-automation-o11y.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem-https.yaml
- charts/provisioner-config-local/recipes/tp-base-on-prem.yaml
- docs/recipes/k8s/cloud/deploy-tp-gke.yaml
- docs/recipes/tp-base/tp-base-on-prem-https.yaml
- docs/recipes/tp-base/tp-base-on-prem.yaml
* disable activation server by default
* remove allowSnippetAnnotations
* externalize ingress version
> 2025 week 18 update 2

- charts/provisioner-config-local/Chart.yaml
- charts/provisioner-config-local/config/pp-deploy-cp-core-on-prem.yaml
- charts/provisioner-config-local/config/pp-undeploy-cp.yaml
- charts/provisioner-config-local/recipes/pp-deploy-cp-core-on-prem.yaml
- docs/recipes/automation/tp-setup/bootstrap/mcps/tp_mcp_server/mcp-server.py
- docs/recipes/automation/tp-setup/bootstrap/page_object/po_dataplane.py
- docs/recipes/controlplane/tp-cp.yaml
- docs/recipes/k8s/cloud/deploy-tp-eks.yaml
* Update TIBCO Platform default version to 1.7.0
* Add graph email support
* adjust MCP server
* add customized certificate support 
* add ARO support
> 2025 week 22 update

- docs/recipes/automation/cloud/bastion/README.md
- docs/recipes/automation/cloud/bastion/_common.sh
- docs/recipes/automation/cloud/bastion/setup-dp-aks-platformprovisioner.sh
- Updated steps for helm install because the URL for it changed.
- Added documentation information about how to obtain the ACCOUNT info
- Added code that if key is not found in recipe global variable, it will be added.
- Added in config.props ability to override instance type for AKS
- Added documentation in README.md that if config.props file is generated, to update the config values and re-execute script
> Minor functionality and documentation tweaks
